server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: gateway-service
  profiles:
    active: local
  cloud:
   gateway:
      routes:
      - id: hr-payroll
        uri: lb://hr-payroll/payments
        predicates:
        - Path=/payments/**
      - id: hr-worker
        uri: lb://hr-worker/workers
        predicates:
        - Path=/workers/**
      - id: hr-user
        uri: lb://hr-user/users
        predicates:
        - Path=/users/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
